C****BRAGFT****BRAGFT****BRAGFT****BRAGFT****BRAGFT****
C...
C...	IDENTIFICATION:  ROUTINE BRAGFT
C...
C...	THIS ROUTINE IS A DISPATCHER FOR THE LINE 
C...	FITTING ROUTINES.  AFTER ALL PERTINENT DATA
C...	IS ENTERRED, THE LINE FITTING ROUTINES ARE
C...	CALLED. 
C...
C******************************************************
      IMPLICIT NONE
      CHARACTER*60	MODID
      CHARACTER*60    OUTFIL
      CHARACTER(1)    YN
      CHARACTER*60    PARMFILE
      REAL*8          WEIGHT
      INTEGER         MAXPAR,MAXDAT,LUNI    
      INTEGER         J,NCHAR,I,IFLAG             
	BYTE		    TITLE(40)                        
	PARAMETER	    (MAXPAR=20)
	PARAMETER	    (MAXDAT=2000)
	COMMON		    /BLK1/B(20),P(20),N,M,K
	COMMON		    /BLK6/WEIGHT(MAXDAT)
      COMMON		    /LBLS/LABEL(20)
	COMMON		    /BRAGG1/X,Y,RRR                             
	COMMON		    /BRAGG2/NARRAY,IB   
	COMMON		    /BRAGG3/START
	COMMON		    /BLANK/ICOUNT
	COMMON		    /IDENT/MODID
	REAL*8          Y(MAXDAT),X(MAXDAT),RRR(MAXDAT) ,START(MAXPAR) 
	INTEGER 	    IB(20)
      REAL*8          B,P
      INTEGER         N,M,K,ICOUNT,NARRAY(8)
      CHARACTER *25	LABEL
      CHARACTER(10)   TIME1,TIME2,TIME3
      INTEGER(2)      TVALS1(8),TVALS2(8)

      ! SAY HELLO
	WRITE(6,999)'LINE-SHAPE ANALYSIS ROUTINE'
      CALL DATE_AND_TIME(TIME1,TIME2,TIME3,TVALS1)  !THIS CALL HELPS TO DETERMINE HOW LONG THE PROGRAM RAN
      
! PROMPT AND RECEIVE FROM INPUT WINDOW
      LUNI=5	
      IFLAG=0
      ICOUNT=0
      
!UNIT 6 IS OUTPUT WINDOW
      WRITE(6,*)'DO YOU WANT TO READ THE PARAMETERS FROM A FILE?'  
      READ(5,90030)YN
90030 FORMAT(A1)
      

      IF(YN.EQ.'Y'.OR.YN.EQ.'y') THEN                             !READ THE PARAMETERS FROM A FILE
          WRITE(6,*)'PARAMETER FILE NAME?= '
          READ (5,90031)PARMFILE
90031     FORMAT(A)
          LUNI=3                                                  !OPEN UNIT 3 FOR THE PARAMETER FILE
          WRITE(6,*)'LUNI,PARMFILE=',LUNI,PARMFILE
          OPEN(UNIT=LUNI,FILE=TRIM(PARMFILE),FORM='FORMATTED',STATUS='OLD')
      ENDIF
      
	WRITE(6,*)LUNI,PARMFILE					!WRITE THE PARAMTER FILE NAME TO THE SCREEN TO CHECK
      
170	WRITE(6,1999)'# OF PARAMETERS   '	    !WRITE THE PARAMETERS READ TO THE SCREEN (UNIT 6)
180	READ(LUNI,90180,ERR=170)NARRAY(3)
90180 FORMAT(I4)
      
      WRITE(6,*)'Number of parameters ',NARRAY(3) 
	IF (NARRAY(3) .GT. MAXPAR) GO TO 190        !CHECK THAT THE NUMBER OF INPUT PARAMETERS DOESN'T EXCEED THE LIMIT (MAXPAR)
	GO TO 171
						!
						! PARAMETER LIMIT ERROR
190	WRITE(6,90190)MAXPAR
90190	FORMAT(/'   * ERROR:  NUMBER OF PARAMETERS MUST NOT EXCEED 'I4,       ' *')
	GO TO 170

171	WRITE(6,1999)' # OF FIXED PARAMETERS  '	! GET MORE DATA
181	READ(LUNI,90180,ERR=171)NARRAY(4)
        WRITE(6,*)'Number of fixed parameters ',NARRAY(4)

!-- GET DATA OUTPUT FILE
200	PRINT *,' ENTER OUTPUT FILESPEC [/=OUTPUT TO TERMINAL] '
	READ (LUNI,90250)OUTFIL
      WRITE(6,*)'OUTPUT FILE SPEC ',OUTFIL
90250 FORMAT(A)		
	IF(OUTFIL.EQ.'/') THEN    
	  NARRAY(7)=6				! WRITE TO THE SCREEN
	ELSE
	  NARRAY(7)=1               !WRITE TO A FILE
	ENDIF

	NARRAY(2)=M
	
290	PRINT *,'ENTER PLOTTING FILE (6 chars) [<CR>=NO PLOTS] '  !THIS IS THE OUTPUT FILE FOR THE Q-INTESNITY DATA WHICH IS OUTPUT 
        READ(LUNI,90290)MODID
90290	FORMAT(A)
        WRITE(6,*)'PLOTTING FILE NAME',MODID

C		*******************************
C		***                         ***
C		***   G R A N D   L O O P   ***
C		***                         ***
C		*******************************
C
300	IF (NARRAY(7).EQ.1) THEN
	   CLOSE(UNIT=1)
	   OPEN(UNIT=1,FILE=OUTFIL)
      ENDIF
						! GET SCAN DATA
      CALL BRGLP1(LUNI)   ! BRGLP1 IS THE SUBROOUTINE THAT READS IN THE DATA- IT'S CONTAINED IN THE FILE "READXYWT_DECLARED" 
						! INITIALIZE TITLE
310       WRITE(6,1999)'$ TITLE:  * '                 
      
	READ(LUNI,90315,ERR=310)(TITLE(J),J=1,40)
90315 FORMAT(40A1)
      NCHAR=40

C		********************************
C		****                       *****
C		****      MINI-LOOP        *****
C		****                       *****
C		******************************** 
						! GET GUESS PARAMETERS
      WRITE(6,*)'NARRAY(7)=',NARRAY(7)
400   WRITE(NARRAY(7),90401)'1 TITLE * ',(TITLE(I),I=1,40)
90401	FORMAT(A,40A1)

	WRITE(NARRAY(7),323)'# OF PARAMETERS=',NARRAY(3)
	CALL BRGLP2(LUNI)   ! BRGLP2   
						! NEW DATA RUN
						! PRINT RESULTS
						!
						!
	IF(IFLAG.EQ.1) GO TO 420
      
      
            CLOSE(UNIT=LUNI)
      
      !************************TEFIT IS THE NONLINEAR MINIMIZATION ROUTINE BASED ON LEVENBERG-MARQUARDT FITTING ALGORITHM 
	CALL TEFIT(Y,X,B,RRR,NARRAY,IB,PARMFILE)
      
420	icount=icount+1         
	CALL BRGPLT(ICOUNT)
						!
999	FORMAT(40A)
1999	FORMAT(/30A)
321	FORMAT(1X,40A1)
!322	FORMAT(A,3(1X,F12.6))
323	FORMAT(30A,I4)
	WRITE(6,*)'PROGRAM FINISHED'
                 
      CALL DATE_AND_TIME(TIME1,TIME2,TIME3,TVALS2)
      WRITE(NARRAY(7),*)'START DATE=',TVALS1(3),'HOUR=',TVALS1(5),'MINUTE=',TVALS1(6),'SEC=',TVALS1(7)
      WRITE(NARRAY(7),*)'END DATE=',TVALS2(3),'HOUR=',TVALS2(5),'MINUTE=',TVALS2(6),'SEC=',TVALS2(7)
           
      
2000  IF (NARRAY(7).EQ.1) CLOSE(UNIT=1)

	
      END
