C---- BRGPLT3----BRGPLT3----BRGPLT3----BRGPLT3----BRGPLT3----
C...
C...		IDENTIFICATION:  ROUTINE BRGPLT
C...		        (BRAGG PLOT)
C...
C...	         ROUTINE WILL WRITES FINAL FIT PARAMETERS TO A FILE *.DAT WHERE * IS THE NAME GIVEN IN THE INPUT FILE AND THE FIT RESULTS ARE PRINTED TO 
C...	         A FILE SPECIFIED IN THE INPUT FILE WITH _P1.DAT APPENDED TO THE NAME 
C...	         THE FORMAT IS 5E15.7 WITH COLUMNS Q,I,0,0,DATA_FLAG (DATA FLAG IS THE PARAMETER FOR MULTIPLE FILES
C...
C...
C...	NOTES ON VARIABLES:
C...	   NARRAY(1) = # OF DATA POINTS
C...	   NARRAY(3) = # OF PARAMETERS (FIXED & VARIED)
C...	   NARRAY(4) = # OF PARAMETERS FIXED
C...	   NARRAY(7) = LOGICAL UNIT FOR OUTPUT
C-----------------------------------------------------------
	SUBROUTINE	BRGPLT(ICOUNT)
      IMPLICIT    NONE
      INTEGER     MAXPAR,MAXERR,MAXDAT
      REAL*8      B,P    
      INTEGER     N,M,K
      INTEGER     LUNO,I,J,IY1,IY2,ICOUNT
      REAL*8      YT                                  
	PARAMETER	(MAXPAR=20)
	PARAMETER	(MAXERR=3)
	PARAMETER	(MAXDAT=2000)
	COMMON		/IDENT/MODID
	COMMON		/BLK1/B(20),P(20),N,M,K
	COMMON		/LBLS/LABEL(20)
	COMMON		/BRAGG1/X,Y,RRR               
	COMMON		/BRAGG2/NARRAY,IB   
	COMMON		/BRAGG3/START
	REAL*8  	Y(MAXDAT),X(MAXDAT),RRR(MAXDAT),START(MAXPAR)
      INTEGER     NARRAY(8)
	DIMENSION	IB(20)                                  
	CHARACTER *25	LABEL
	CHARACTER *67	PLTFIL
	CHARACTER *60	MODID
	INTEGER 	ERRLBL,ERRCNT,IB,IX,INDXSC          
	BYTE		TITLE(40),LINE(0:80)
	DATA		LINE/81*' '/
           

	LUNO = NARRAY(7)
						!
						! PRINT RESULTS
	WRITE(LUNO,90600)TITLE
90600	FORMAT(///40A1)

	WRITE(LUNO,90650)
90650	FORMAT(////'     INITIAL VALUE      FINAL VALUE')
	    DO 690 I=1,NARRAY(3)
	        DO 660 J=1,NARRAY(4)
	        IF (IB(J)-I) 660,665,660
660	        CONTINUE
	    GO TO 670
665	    WRITE(LUNO,90665)I,START(I),B(I),LABEL(I)
90665	    FORMAT(I5,2(5X,F15.5),2X,A25,' <- THIS PARAMETER HELD ',
     1      'FIXED')
	    GO TO 690
670	    WRITE(LUNO,90670)I,START(I),B(I),LABEL(I)
90670	    FORMAT(I5,2(5X,F12.5),2X,A25)
690       CONTINUE

      
C--  WRITE DATA TO FILE FOR PLOTTING [q,I(q),0,0]

725     PLTFIL=ADJUSTR(MODID(1:60))//'_P1.DAT'
C        WRITE(5,777)PLTFIL
C777     FORMAT('NAME=',A20)
	OPEN(UNIT=3,NAME=PLTFIL,STATUS='UNKNOWN',FORM='FORMATTED')
        DO 740 I=1,NARRAY(1)
        YT=Y(I)-RRR(I)
        WRITE(3,741)X(I),YT,0.,0.
!        write(6,741)x(i),y(i),yt,rrr(i)
741     FORMAT(4E15.7)
740     CONTINUE
        CLOSE(UNIT=3)

	RETURN					! GET NEXT RUN
2000	END
