C-----BRGLP1-----BRGLP1-----BRGLP1-----BRGLP1-----BRGLP1-----
C---
C---	IDENTIFICATION:  ROUTINE BRGLP1
C---	        (BRAGG LOOP 1)
C---
C---	THIS ROUTINE READS IN FORMATTED DATA IN ROWS OF Q , I ,SIGMA(I)SQUARE ,SIGMA(Q)SQUARE
C---
C---	NOTES ON VARIABLES:
C---	   NARRAY(1) = # OF DATA POINTS
C--------------------------------------------------------------
	SUBROUTINE	BRGLP1(LUNI)                                       !DISK,,ICODE)
      IMPLICIT    NONE
      INTEGER     MAXDAT,lunf,luni,lcnt
	INTEGER 	IB(20)
	CHARACTER*60	DATFIL
	CHARACTER*1	STYPE
	INTEGER 	ERRLBL                                                      !iplot,ICODE
	INTEGER 	ICONT,NSCN,MN
	REAL*8		SC
	LOGICAL*1	SKIP                                                                    !DISK
	PARAMETER   (MAXDAT=2000)
	REAL*8      	Y(MAXDAT),X(MAXDAT)                   !DID SIMPLY DIMENSION FMT(40) BEFORE
      INTEGER     NARRAY(8) 
      REAL*8        RRR(MAXDAT),DELQ(MAXDAT),DATA_FLAG(MAXDAT)
      REAL*8        WEIGHT,MULT_FAC
      REAL*8      XIN,YIN,WIN,DELIN,DATAFIN
	COMMON		/BLK6/WEIGHT(MAXDAT)
	COMMON		/BRAGG1/X,Y,RRR                 !,FMT
	COMMON		/BRAGG2/NARRAY,IB         !iplot,IX,INDXSC
      COMMON          /BRAGG4/DELQ
	COMMON		/PHICOM/DATA_FLAG
	DATA		LUNF/4/
C---

	PRINT *,'*** ENTER DATA FILE NAME***'
	READ (LUNI,990)DATFIL
990	FORMAT (A)
      IF(LUNI.EQ.3)WRITE(6,*)'DATA FILE NAME IS ',DATFIL
C      WRITE(6,990)
C  990 FORMAT(//'***ENTER FILE NAME***')
C      READ(LUNI,980)DATFIL
c  980 FORMAT(A40)
c      WRITE(6,*)'DATA FILE NAME ',datfil
C      WRITE(6,*)'LUNF ',LUNF
      OPEN(UNIT=LUNF,FILE=DATFIL,FORM='FORMATTED',ERR=999,STATUS='OLD')
      WRITE(6,*)'FILE OPENED'

      DO 100 LCNT=1,2000 
      READ(4,*,END=960)XIN,YIN,WIN,DELIN,DATAFIN      !READ IN THE DATA Q,I,SIGMA(I)SQUARE,SIGMA(Q)SQUARE,DATA FLAG-- DATA FLAG CAN BE USED TO READ IN SEVERAL FILES TO BE 
                                                      !SIMULTANEOUSLY CALCULATED.  FOR EXAMPLE WE COULD READ IN RADIAL DATA TAKEN AT DIFFERENT ANGLES ON THE SANS DETECTOR  
      X(LCNT)=XIN
      Y(LCNT)=YIN
      WEIGHT(LCNT)=WIN
      DELQ(LCNT)=DELIN
      DATA_FLAG(LCNT)=DATAFIN
      WEIGHT(LCNT)=1.0D0/(WEIGHT(LCNT))    ! THIS IS 1/(PROPER VARIANCE). THIS WILL BE USED TO WEIGHT THE DATA POINTS IN THE FIT
  100 CONTINUE
      
      
  960 NARRAY(1)=LCNT-1                    !NARRAY(1) IS THE NUMBER OF DATA POINTS

      CLOSE (UNIT=LUNF)
      RETURN
  999 WRITE(6,*)'ERROR'                   !IF THERE IS AN ERROR IN THE DATA FILE PRINT THIS ERROR MESSAGE
      END
