		subroutine Ncylffac_SECT_FIT (X,IQ,NCYL,COSPSI,SINPSI)
!**************************
!**********************************************************************************************
    
!    THIS IS FOR THE GRADIENT-VORTICITY DIRECTION
    
!**********************************************************************************************    
!  THIS IS THE ROUTINE THAT HAS MOST OF THE CALULATIONS FOR THE FUNCTIONS NEEDED FOR 
!  5 CYLINDER CALCULATIONS


! THIS HAS AN ARBITRAY MULIPLIER OF 1000.  THE RESULT IS THAT THE MONTE CARLO INTEGRATION 
! IS ALMOST 1/3 THE TIME BUT GIVES THE SAME ANSWER!!!!!!!!!!!!!


!X=[THETA0,THETA1,THETA2,PHI0,PHI1,PHI2] 
! This is a FIVE cylinder form factor including the probablity for each cylinder- this DOES include 
! both orientations of flow
!COMMON STUFF,Q,PSI,SHEARRATE, RADIUS CYLINDER, LENGTH CYLINDER, HYDRO LENGTH


!PRINT,'HERE', QPASS
!		IMPLICIT NONE
		COMMON /STUFF/QPASS,PHIO,RCYL,LCYL,STRETCH
		integer NCYL
!        parameter (NCYL= 7)			!NUMBER OF CYLINDERS


!		REAL  P_TH_PH1A
		double precision GAMMAI(NCYL)	!,GAMMAI_MINUS(NCYL)		TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
		double precision X((2*NCYL)+1)
		double precision THETA(NCYL), PHI(NCYL)
		double precision COSPSI, SINPSI, PI
		double precision COSTHETA(NCYL), SINTHETA(NCYL),COSPHI(NCYL),SINPHI(NCYL)
		double precision SX(NCYL),SY(NCYL)		!,SZ_MINUS(NCYL),SX_MINUS(NCYL)		TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE

		DOUBLE PRECISION QPASS,PHIO,RCYL,LCYL,STRETCH,FQ(2)
		double precision QDOTS(NCYL)					!,QDOTS_MINUS(NCYL)			TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE


		double precision F1(NCYL)		!,F1_MINUS(NCYL)							TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
		double precision PROB0(NCYL)
		double precision TEM1,TEM2,IQ,IQ1  !, TEM1_MINUS,TEM2_MINUS				TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE

        PI=4.0D0*DATAN(1.0D0)  

!		COSPSI=COS(X(1))
!		SINPSI=SIN(X(1))
!		WRITE(6,*)'IN FUNCTION: QPASS,COSPSI,SINPSI',QPASS,COSPSI,SINPSI
        
		THETA=X(1:NCYL)
		PHI=X(NCYL+1:NCYL*2)

		COSTHETA=COS(THETA)
		SINTHETA=SIN(THETA)
		COSPHI=COS(PHI)
		SINPHI=SIN(PHI)
		GAMMAI=ACOS(COSPSI*COSPHI*SINTHETA+SINPSI*SINTHETA*SINPHI)
!		GAMMAI_MINUS=ACOS(-COSPSI*COSPHI*SINTHETA+SINPSI*COSTHETA)   TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE

		SX(1)=DBLE(0.)
		SY(1)=DBLE(0.)
!		SX_MINUS(1)=DBLE(0.)										TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
!		SZ_MINUS(1)=DBLE(0.)										TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE

		QDOTS(1)=DBLE(0.)
!		QDOTS_MINUS(1)=DBLE(0.)										TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE

			DO 20 J=2,NCYL
			SX(J)=SX(J-1)+(COSPHI(J)*SINTHETA(J)+COSPHI(J-1)*SINTHETA(J-1))	
            SY(J)=SY(J-1)+(SINPHI(J)*SINTHETA(J)+SINPHI(J-1)*SINTHETA(J-1))
 			QDOTS(J)= QPASS*LCYL/2.*(COSPSI*SX(J)+SINPSI*SY(J))
!			QDOTS_MINUS(J)=QPASS*LCYL/2.*(-COSPSI*SX(J)+SINPSI*SZ(J))	TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
 20			CONTINUE


		DO 10 II=1,NCYL
		call CFF2(GAMMAI(II),QPASS,RCYL,LCYL,FQ(1))
!		call CFF2(GAMMAI_MINUS(II),QPASS,RCYL,LCYL,FQ(2))			TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE	
        F1(II)= FQ(1)
!		F1_MINUS(II)=FQ(2)											TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
10      CONTINUE

		call P_TH_PH1A_Ncyl(THETA,PHI,prob0,NCYL)

		TEM1=F1(1)
!		TEM1_MINUS=F1_MINUS(1)										TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
		TEM2=DBLE(0.)
!		TEM2_MINUS=DBLE(0.)											TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE

		DO 40 KK=2,NCYL
		TEM1=TEM1+F1(KK)*COS(QDOTS(KK))
		TEM2=TEM2+F1(KK)*SIN(QDOTS(KK))
!		TEM1_MINUS=TEM1_MINUS+F1_MINUS(KK)*COS(QDOTS_MINUS(KK))		TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
!		TEM2_MINUS=TEM2_MINUS+F1_MINUS(KK)*SIN(QDOTS_MINUS(KK))		TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
40		CONTINUE




		IQ=(TEM1*TEM1+TEM2*TEM2)			!+(TEM1_MINUS*TEM1_MINUS+TEM2_MINUS*TEM2_MINUS)		TAKE THIS MINUS TERMS OUT SINCE YOU AREN'T GOING TJROUGH THE COUETTE CELL TWICE
                                            !Jz added: don't multiply by factor of 2!
		IQ1=DBLE(1.)
			DO 50 JJ=1,NCYL
			IQ1=IQ1*SINTHETA(JJ)*PROB0(JJ)
50          CONTINUE

		IQ=IQ*IQ1
		IQ=IQ*1000.  !!THIS HAS AN ARBITRAY MULIPLIER OF 1000.
        

		end