	SUBROUTINE MODEL(F,Y,X,RE,RRR,JP)
      !THIS SUBROUTINE DISPATCHES THE MODEL ROUTINE IN THE FIT AND CALCULATES THE RESIDUAL
      IMPLICIT    NONE
	COMMON /BLK1/B(20),P(20),N,M,K
	COMMON /BLK6/WEIGHT(2000) 
	COMMON /BLK7/ITAYL
	COMMON /BLK8/LJ
      COMMON /BRAGG4/DELQ
!	COMMON /MODL8/QZ,DQZ
	COMMON /PHICOM/DATA_FLAG      
      
      INTEGER     MAXDAT,MAXPAR				!
	PARAMETER   (MAXDAT=2000)   !MAXIMUM NUMBER OF DATA POINTS READ
	PARAMETER   (MAXPAR=20)	    ! MAXIMUM NUMBER OF PARAMETERS, B
      
      INTEGER     I,JP,N,M,K      
      INTEGER     MM,NB,ITAYL,LJ                
      REAL*8      Y(MAXDAT),X(MAXDAT),RRR(MAXDAT),DELQ(MAXDAT),DATA_FLAG(MAXDAT)
	CHARACTER(1) REPLY
	REAL*8      QZ(N),DQZ(N),DFLAG(N),FNA(N),F(N),RE(N)
      REAL*8      B,P,WEIGHT

     	RE=0.0D0
      F=0.0D0 
      QZ = X(1:N)
      DQZ=DELQ(1:N)   
	DFLAG=DATA_FLAG(1:N)
      RRR=0.0D0
	CALL CROSSC(FNA,QZ,DQZ,DFLAG)
      F = FNA
	RE = Y(1:N) - F
	GOTO (600,500,600,700),JP
500   JP=3
600   F = F* SQRT(WEIGHT(1:N))
	RE = RE * SQRT(WEIGHT(1:N))
	RETURN
700	RRR(1:N) = RE
	RETURN
	END


	SUBROUTINE	CROSSC(FNA2,Q,DQZ,DFLAG)
!THIS IS THE MODEL PROGRAM TO CALCULATE THE SCATTERED INTENSITY AS A FUNC OF Q 
!FOR N CONNECTED CYCLINDERS UNDER SHEAR- WRITTEN BY GREG SMITH JANUARY 2021; UPDATED DECEMBER 2022
      
      !THIS VERSION   1.IS ONLY FOR THE ZERO SHEAR CASE
      !               2. REMOVES THE PROBABLILITY CALCULATION
      !               3. CALCULATES S(Q) BASED ON PRISM FORM FACTOR. USES FORM FACTOR OF THIN ROD AS THE Q-DEPENDENT PREFACTOR (SEE PEDERSEN AND SCHURTENBERGER 2002 OR CHEN, BUTLER, MAGID 2006)
      !               4. THIS SUBROUTIME CALLS THE MODEL SUBFUNCTIONS WHICH CALCULATE THE SCATTERING FUNCTION FOR THE DATA POINTS INPUT PLUS 8 DATA POINTS BEFORE AND AFTER END BEGINNING AND END OF THE ACTUAL DATA
      !                   iN THIS WAY THE RESOLUTION CAN BE CALCULATED USING THE TRAPAZOID RULE 
      
      IMPLICIT NONE
	COMMON /BLK1/B(20),P(20),N,M,K
      COMMON /R_AND_N_BLK/RSQAVG,NCYLAVG 
	INTEGER MAXDAT,MAXPAR,NPRI
      REAL*8 B,P,RE
      INTEGER KK,N,M,K
	PARAMETER (MAXPAR=20)	! MAXIMUM NUMBER OF PARAMETERS
      INTEGER NARRAY,STEP,II,NS,NCYL,LCNT,I,SHEARCNT,III,J,JJ,III1
      INTEGER LENARR_LENGTH,NCALL
      REAL*8 YOUT(N+18) ,Q(N),COSPSI(N+18),SINPSI(N+18)  !TO DO RESOLUTION CALCULATION, CALCULATES 9 POINTS LOWER AND 9 POINTS HIGHER THAN THE MEASURED Q VALUES
      REAL*8 YOUT1(N+18)
      REAL*8 QI,CS(N+18),SS(N+18),NCYLAVG,PI
	REAL*8 DQZ(N),DFLAG(N+18),LC
      REAL*8  YI,SIGMAI,SIGMAQ(N),DATA_FLAG,QIN
      REAL*8 CSYQYL(N+18),FNA2(N),FUNC,CQ(N+18),CQ1(N+18)
      REAL*8 LENARR(60)
      REAL*8 BETA,INT1,INT2,RSQAVG,NCYLINT
      REAL*8 QP(N+18),DELTAQ(N+17),QCEN(N+17),TERM1,TERM2,TERM3,TERM4
      REAL*16 SINXOX_INT(N+18),QL(N+18),TERM0(N+18),TNP1
      REAL*16 TNP1_FACT,QL1(130)
      CHARACTER*4 NUMCHAR
      
      
      COSPSI=0.0D0
      SINPSI=0.0D0
      !DEFINE EXTENDED QRANGE, DFLAG RANGE
      NPRI=N+18
      QP(9:N+8)=Q
      DFLAG(9:N+8)=DFLAG
      DFLAG(1:8)=0.0D0
      DFLAG(N+8:NPRI)=0.0D0
      
      !******************************!!!!!!!!!!!!!!!!!!!!!!!!!
      !STEP SIZE BETWEEN 0 AND FIRST Q-POINT IN THIS DATA SET (WHICH IS 4.506E-3) IS 5.3E-4 WHICH WILL GIVE 8 ADDITIONAL Q-POINTS- ARTIFICIAL CHOICE FOR ESOLUTION CALC
      !THIS IS DIFFERENT FOR DIFFERENT DATA SETS- NEEDS TO BE AUTOMATED IN GENERAL TO CALCULATE THE FIRST DELTA
      QP(1:8)=5.3D-4*[1,2,3,4,5,6,7,8]
      !GO PAST Q-MAX BY 4*SIGMA(QMAX)
      QP(N+9:NPRI)=Q(N)+4.0D0*SQRT(DQZ(N))/10.0D0*[1,2,3,4,5,6,7,8,9,10]

          DO 27 J=1,NPRI
              IF (DFLAG(J).EQ.0.)   COSPSI(J)=1.0D0
              IF (DFLAG(J).EQ. 90.) SINPSI(J)=1.0D0
27        CONTINUE

!   B(1) THIS IS AN ARBITRARY AMPLITUDE correction (SET TO 1 FOR NORMALIZED DATA)
!   B(2) THIS IS THE RADIUS OF THE CYLINDERS
!   B(3) THIS IS THE CYLINDER LENGTH (REALTED TO THE KUHN LENGTH)
!   B(4) AN ADdITIVE BACKGROUND TERM; ONLY IMPORTANT AT HIGH Q
!   B(5) VOLUME FRACTION OF MICELLES TIMES THE SCATTERING LENGTH DENISTY SQUARE /10**19 CM-4
!   B(6) AMPLITUDE MULTIPLIER FOR PRISM Q-DEPENDENT TERM IN STRUCTURE FACTOR 
!   B(7) THE AVERAGE CYLINDER LENGTH USED IN THE THE DISTRIBUTION OF CHAIN LENGTH IN CATES 
!   B(8) IS THE MAXIMUM NUMBER OF CYLINDERS IN THE LONGEEST CHAIN CALCULATED
!   B(9) IS THE GAUSSIAN SIGMA FOR SMEARING THE CYLINDER RADII
!   B(10) IS THE NUMBER OF ITERATIONS USED IN THE VEGAS INTEGRATION CALCULATIONS
!   B(11) IS THE INTERACTION LENGTH USED IN THE PRISM STRUCTURE FACTOR- (I.E. THE LENGTH OF THE THIN ROD USED IN THE STRUCTURE FACTOR CALCULATION)
      
      PI=4.0D0*DATAN(1.0D0)  
      BETA=(1-B(6))/B(6)      !DEFINE BETA FROM S(Q=0)
      YOUT=0.0D0
      CQ1=0.0D0
      LC=B(7)
      LENARR=0.0D0
      LENARR_LENGTH=INT(B(8))
      LENARR=(/1:60/)
      LENARR=LENARR/LC
      LENARR=DEXP(-LENARR)
      NCYLAVG=0.0D0
      NCYLINT=0.0D0
      DELTAQ=QP(2:NPRI)-QP(1:NPRI-1)      ! DEFINE BIN WIDTHS FOR RESOLUTION CALC
      QCEN=(QP(2:NPRI)+QP(1:NPRI))/2.0D0       !DEFINE THE CENTER OF EACH OF THE Q BINS FOR THE RESOLUTION CALCULATION
      NCALL=B(10)
         

!**************************************************************************************
!     LOOP OVER THE NUMBER OF THE DISTRIBUTION OF CHAINS LENGTHS (I-CYLINDER, 2-CYLINDERS, ETC, UP TO THE LONGEST CHAIN LENGTH SET AT )
          DO 805 III=1,LENARR_LENGTH
          NCYL=III
          CS=COSPSI
          SS=SINPSI
************************************************************CALL THE SCATTERING CALCULATION ROUTINES**************
          CALL CSY_MULTI(QP,CS,SS,CSYQYL,NCYL,NPRI,NCALL)
*******************************************************************************************************
          YOUT1=CSYQYL    
          NCYLINT=NCYLINT+REAL(III)*LENARR(III)  
          YOUT=YOUT+YOUT1*LENARR(III)*DBLE(NCYL)  !BRING N INSIDE INTEGRAL  
  805     CONTINUE     
 
      NCYLAVG=NCYLINT/SUM(LENARR(1:LENARR_LENGTH))   
      YOUT=YOUT/NCYLINT
      
!      ******************************************
!      Calculate form factor of thin rod
!             first calculate integral       
!     This section uses high precision to get the value of the integral through the series solution
      SINXOX_INT=REAL(0.,16)
      QL=REAL(QP,16)*REAL(B(11),16)                   !B(11) IS A APPARENT LENGTH SCALE FOR THE THIN ROD AND ISN'T THE SAME AS THE LENGTH OF THE CYLINDERS
      TERM0=REAL(0.,16)
          DO 121 I=0,150
          TNP1=(REAL(2.,16)*REAL(I,16))+REAL(1.,16)
          TNP1_FACT=REAL(1.,16)
!             ***********************************************
!              CALCULATE 2N+1 FACTORIAL
              DO 122 J=1,INT(TNP1)
              TNP1_FACT=TNP1_FACT*REAL(J,16)  
  122         CONTINUE
!             ***********************************************              
          TERM0=(REAL(-1.,16)**REAL(I,16))*(QL**TNP1)/(TNP1)/(TNP1_FACT)
          SINXOX_INT=SINXOX_INT+TERM0
  121     CONTINUE
          
      CQ1=REAL((2.0D0*SINXOX_INT/QL)-(4.0D0*(SIN(QL/2.0D0)/QL)*(SIN(QL/2.0D0)/QL)),8)    
!**************************************************************      

  ! CALCULATE THE MEAN OF THE CYLINDER RADIUS  FOR THE NORMALIZATION       
      CALL NORMALCALCS(B(2),B(9),0.0D0,FUNC)   !FUNCNUM=0 IS EXP(-(R-R0)^2/2*SIGMA^2)
      INT1=FUNC
      CALL NORMALCALCS(B(2),B(9),1.0D0,FUNC)   !FUNCNUM=1 IS R^2*EXP(-(R-R0)^2/2*SIGMA^2)
      INT2=FUNC
      RSQAVG=INT2/INT1
      YOUT=YOUT/INT2                          !DIVIDE BY INTEGRAL OF R^2*EXP(-(R-R0)^2/2*SIGMA^2) TO GET NORMALIZED P(Q)
          
                    
          DO 740 I=1,NPRI
          YOUT(I)=YOUT(I)/(1.0D0+BETA*CQ1(I)*YOUT(I))     !PRISM STYLE FORM FACTOR WITH Q-DEPENDENT CQ1
740       CONTINUE                
          
      
      YOUT=B(5)*YOUT                              !SCALED TO PHI*(DELTA SLD)**2 WHICH IS PARAMETER B(7)IN 10-19 CM-1
      YOUT=PI*B(3)*RSQAVG*NCYLAVG*YOUT*1.0E-5   !SCALED TO VOLUME OF A "MICELLE" WHICH IS THE VOLUME OF A CYLINDER X NUMBER OF CYLINDER ; THE LAST FACTOR CONVERTS THE DIMESNIONS IN ANGSTROMS TO CM-1    
      
      YOUT=B(1)*YOUT+B(4)


      
      !NOW PERFORM RESOLUTION CALCULATION USE THE GREATER OF +/20 STEPS OR FORM Q(1) TO +20 STEPS
      SIGMAQ=SQRT(DQZ)
      FNA2=0.0D0
          DO 300 I=1,N   !USING N SINCE THESE ARE OUR FINAL POINTS
          TERM1=0.0D0
          TERM2=0.0D0
          TERM3=0.0D0
          TERM4=0.0D0
              DO 301 J=-20,19
                  IF(I+J+8.LT.1)GOTO 340
                  IF(I+J.GT.NPRI) GOTO 340
              TERM1=Q(I)-QCEN(I+J+8)
              TERM3=(TERM1*TERM1)/2.0D0/SIGMAQ(I)/SIGMAQ(I)
              TERM2=DELTAQ(I+J+8)/SIGMAQ(I)/DSQRT(8.0D0*PI)
              TERM4=YOUT(I+J+9)+YOUT(I+J+8)
              FNA2(I)=FNA2(I)+TERM2*TERM4*DEXP(-TERM3)   
  340             CONTINUE
  301         CONTINUE
  300     CONTINUE        

      GOTO 998
  999 WRITE(6,*)'ERROR'
  998 CONTINUE

      END
 
      
      
      
      
      
      
      
      
      
      
      
      
  
